b# Branch Protection Rules Configuration
# This file documents the branch protection settings that should be configured in GitHub
# Based on requirements from docs/REQUIREMENTS_SPECIFICATION.md

# Main branch protection (Production)
main:
  required_status_checks:
    strict: true
    contexts:
      # REQ-17.1: Automated testing on code commits
      - 'Lint and Format Check'
      - 'POC Specification Tests'
      - 'Unit Tests (20.x)'
      - 'Unit Tests (22.x)'
      - 'Security Scan'
      - 'Build Applications'
      - 'Integration Tests'
      - 'Performance Tests'
  enforce_admins: false
  required_pull_request_reviews:
    # REQ-17.2: Block merging if tests fail
    required_approving_review_count: 2
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    require_last_push_approval: true
  restrictions:
    users: []
    teams: ['emotion-recognition-team']
  allow_force_pushes: false
  allow_deletions: false
  # REQ-10.5: Fail builds below 90% coverage
  required_checks_policy: 'strict'

# Develop branch protection (Staging)
develop:
  required_status_checks:
    strict: true
    contexts:
      # REQ-17.1: Automated testing on code commits
      - 'Lint and Format Check'
      - 'POC Specification Tests'
      - 'Unit Tests (20.x)'
      - 'Unit Tests (22.x)'
      - 'Security Scan'
      - 'Build Applications'
      - 'Integration Tests'
  enforce_admins: false
  required_pull_request_reviews:
    # REQ-17.2: Automated tests complete within 15 minutes
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: false
  restrictions:
    users: []
    teams: ['emotion-recognition-team']
  allow_force_pushes: false
  allow_deletions: false

# Quality Gates Configuration
quality_gates:
  # REQ-10.1: >90% code coverage requirement
  coverage_threshold: 90
  # REQ-10.2: Each test completes within 100ms
  test_performance_threshold: 100
  # REQ-17.2: Tests complete within 15 minutes
  ci_timeout_minutes: 15
  # REQ-14.1: <500ms latency requirement
  performance_latency_threshold: 500
  # REQ-14.2: Resource usage limits
  cpu_usage_threshold: 80
  memory_usage_threshold: 4096
